# Generated by Django 5.1.1 on 2025-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0016_alter_product_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://thumb.ac-illust.com/73/7387030e5a5600726e5309496353969a_t.jpeg'),
        ),
    ]
